services:
    mysql:
        image: nimbuskycdb:1.0
        ports:
            - "5555:3306"
        environment:
            - MYSQL_USER=developer
            - MYSQL_PASSWORD=W2.e3-r4.t5
            - MYSQL_DATABASE=NimbusKYC
        volumes:
            - "./conf.d:/etc/mysql/conf.d:ro"
